### PR TITLE
Updating SuiteSparse to 5.8.1

### PR DESCRIPTION
**Pull request by AnHeuermann**
I'm trying to update [SuiteSparse](https://people.engr.tamu.edu/davis/suitesparse.html) to [version 5.8.1](https://github.com/DrTimothyAldenDavis/SuiteSparse/releases).

### Related ticket
[trac ticket 6362](https://trac.openmodelica.org/OpenModelica/ticket/6362)

### CODE REVIEW

**Comment by AnHeuermann** [comment]
Maybe we should create a fork of https://github.com/DrTimothyAldenDavis/SuiteSparse and add this as a submodule and don't copy the files into here.
We deleted everything we don't use, but the only changes we really have is a CMakeList.txt file we created for the repo.

**Comment by sjoelund** [comment]
For other projects, we used git subtree instead. It works pretty well, allows to have your own patches, and doesn't rely on yet another repository

**Comment by AnHeuermann** [comment]
Sounds good, but I have not used git subtree before. I'll check on it on Monday.

**Comment by sjoelund** [comment]
It's used for ModelicaExternalC. There is a README.

**Comment by casella** [comment]
BTW, @fedetft pointed out to me this notification on the SuiteSparse [README.md](https://github.com/DrTimothyAldenDavis/SuiteSparse):

>  NOTE: Use of the Intel MKL BLAS is strongly recommended. A recent OpenBLAS can result in severe performance degradation. The reason for this is being investigated, and this may be resolved in the near future. Ignore the comments about OpenBLAS in the various user guides; those are out of date.

I found this a bit disturbing. Do you know anything about it? Which version of OpenBLAS are we using?

**Comment by sjoelund** [comment]
> Which version of OpenBLAS are we using?

On Linux? Usually none (we use whatever system version of lapack is installed, which is usually reference lapack)

**Comment by AnHeuermann** [comment]
>Which version of OpenBLAS are we using?

On Windows we are linking to OpenBlas v0.3.12 from OMDev.

It would be quiet interesting to see how much of a difference it would be to use the Lapack and Blas libraries from the Intel MKL, but I don't have access to it.
Also I can't see a way how we could add it to the Windows installer. We link statically to OpenBlas, so only if you build OpenModelica yourself (and have a Intel CPU) you can change the Lapack used in different parts of the compiler. We can of course change that and link dynamic to lapack oand/or SuiteSparse. But who on Windows has Lapack or SuiteSparse installed in a way that it would be possible to link to them? Also it would change a lot of our linking and potentially break FMUs.

**Pull request merged**
