### PR TITLE
Modelica externalc update

### PR DESCRIPTION
**Pull request by mahge**

### CODE REVIEW

**Comment by sjoelund** [comment]
Thanks. Seems I forgot this one, but did you squash when you merged this? That can cause problems since the commit referred to in OpenModelica.git no longer exists.

**Comment by mahge** [comment]
I think Lennart just deleted the branch. Otherwise it should have worked fine. You should open a PR to OM with the new tip of master.

**Comment by sjoelund** [comment]
I think it still works. I have removed the squash and rebase options for PRs on this repo now. I could just push --force it I suppose. That should be easier

**Comment by mahge** [comment]
Why are you solving unrelated problems to pass the fault to something else. Just push your branch if you still have it. Otherwise open a PR to OM.

**Comment by sjoelund** [comment]
> Why are you solving unrelated problems to pass the fault to something else. Just push your branch if you still have it. Otherwise open a PR to OM.

For 3rdParty, we use this workflow: https://github.com/OpenModelica/OpenModelica/blob/master/CONTRIBUTING.md
The exact same commit ends up in the master

**Comment by mahge** [comment]
We are here because you did not follow the workflow you just specified like it is something for us. 

Why does everything has to be a competition with you.

If you are not going to open a new PR to OM, and if you still have the branch `modelica-externalc-update`, push it here. So everything continues to work until the next update to 3rdParty.  

> The exact same commit ends up in the master

I am guessing you are talking about the commit after rebase. I do not think it does. hashes depend on timestamps. You will need to update your PR on OM with the new hash after rebasing 3rdParty. But again that has nothing to do with the case here.

**Comment by sjoelund** [comment]
Note that I did not write the workflow. It probably needs to be updated. But we don't want a lot of branches on 3rdParty and the workflow is to create branches first because otherwise Jenkins fails.

**Comment by mahge** [comment]
> But we don't want a lot of branches on 3rdParty and the workflow is to create branches first because otherwise Jenkins fails

Again this is not true as well. You can have your branch on your fork and test your PR on Jenkins. The reference to 3rdParty in OM is qualified.

**Comment by sjoelund** [comment]
> Again this is not true as well. You can have your branch on your fork and test your PR on Jenkins. The reference to 3rdParty in OM is qualified.

Keep in mind that Github keeps changing how it works. It for sure has not worked in the past. That's why we have the working workflow to follow. Github also does garbage collection every now and then so commits that are not listed on a ref can be removed.

Pull requests are bad for submodules because github rebase rewrites the commits (unlike regular git rebase), or squashes... So you need to change the OpenModelica.git pull request after pushing here.

**Comment by mahge** [comment]
> Keep in mind that Github keeps changing how it works. 

What does fetching a submodule have to do with github? why would Jenkins care it is github when issuing git commands?


> Pull requests are bad for submodules because github rebase rewrites the commits (unlike regular git rebase), or squashes... So you need to change the OpenModelica.git pull request after pushing here.

Did I not just correct you with this exact statement here: https://github.com/OpenModelica/OMCompiler-3rdParty/pull/103#issuecomment-960570590. Why are brining it like it is what you said originally.

You can wiggle all you want as usual. But I am past the point to humor you because you crossed a line recently. We are done here.

**Comment by sjoelund** [comment]
> What does fetching a submodule have to do with github? why would Jenkins care it is github when issuing git commands?

It fetches from github.com/OpenModelica/OMCompiler-3rdParty - never any other repository

**Pull request merged**
