### PR TITLE
Allow parsing the files with non-ascii characters in path

### PR DESCRIPTION
**Pull request by adeas31**

### CODE REVIEW

**Comment by casella** [comment]
@adeas31, does this solve [#5437](https://trac.openmodelica.org/OpenModelica/ticket/5437)?

**Comment by adeas31** [comment]
Yes and hopefully [#5192](https://trac.openmodelica.org/OpenModelica/ticket/5192) as well. See also https://github.com/OpenModelica/OpenModelica/pull/201

**Comment by casella** [comment]
Excellent! Do you have plans to test this yourself, or should I involve Russian users to try that out? We can ask @trosinenko, and also some students of mine from Russia that had issues with OMNotebook when doing some lab activity in class.

**Comment by adeas31** [comment]
Well I already tested it myself with Swedish alphabets. More testers are good and that is why I pushed it in so people can try the nightly builds.

**Comment by casella** [comment]
OK, thanks!

**Comment by casella** [comment]
OK. When the nightly is built I will suggest my students to test it. @atrosinenko should get notifications from github and trac

**Comment by atrosinenko** [comment]
I tried to install OpenModelica-1.14 build 26504 under regular user (with latin-only letters in its name), then launched it under user named "Пользователь" (i.e. User in Russian). I got the assertion message with the following logs:

**omeditcommands.log:**
```
getVersion(OpenModelica); getErrorString();
getInstallationDirectoryPath(); getErrorString();
cd("C:/Users/Пользователь/AppData/Local/Temp/OpenModelica/OMEdit/"); getErrorString();
getModelicaPath(); getErrorString();
errors:=getMessagesStringInternal(); getErrorString();
size(errors,1); getErrorString();
numProcessors(); getErrorString();
```
**omediterror:**
```
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directory: Системе не удается найти указанный путь: "C:/Users/РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ/AppData/Local/Temp/OpenModelica/OMEdit/"
```

**omeditoutput:**
```
info:    Set temp directory to    "C:/Users\Пользователь\AppData\Local\Temp\OpenModelica\OMEdit"
info:    Set working directory to "C:/Users\Пользователь\AppData\Local\Temp\OpenModelica\OMEdit"
```

I would specially mention the `omediterror` file: it features an error message "Системе не удается найти указанный путь" (System cannot find the path specified), followed by the string containing `РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ` -- this looks like the word "Пользователь" incorrectly converted between multibyte encoding (UTF-8?) and CP1251 / CP866 / whatever.

**Comment by adeas31** [comment]
@atrosinenko that error you see is from OMSimulator that has been fixed in https://github.com/OpenModelica/OMSimulator/commit/1b5430449cb859fa7a91de08497174a44ae97a21. Note that the fix just avoids the crash and OMSimulator is unusable in that case.

I fixed few more things in https://github.com/OpenModelica/OpenModelica/commit/33fb7b969896eb9fb1b073f3737f58c4bcf0eaa4 and made it possible to load and simulate Modelica models even if the path contains the special characters.

**Pull request merged**
