### PR TITLE
Update FMIL to revision 10948

### PR DESCRIPTION
**Pull request by lochel**
It seems that the following patches are no longer required:

* 8640f827 quard vsnprintf for macos [@adrpo, 8 months ago]

### CODE REVIEW

**Comment by lochel** [comment]
@adrpo @sjoelund Should we push your patches also to `OMSimulator/3rdParty/FMIL`?

**Comment by OpenModelica-Hudson** [comment]
The following pull requests are now being [tested](https://test.openmodelica.org/hudson/job/OpenModelica_TEST_PULL_REQUEST/6107//console). It may take a while, depending on the workload.
Belonging to [master]:
  - OpenModelica/OMCompiler-3rdParty#32

The changes will be pushed if all tests run successfully.

**Comment by lochel** [comment]
> Mine for sure.

OpenModelica/OMFMISimulator-3rdParty#37

**Comment by OpenModelica-Hudson** [comment]
**[Linux:](https://test.openmodelica.org/hudson/job/OpenModelica_TEST_PULL_REQUEST/6107/)** All tests were successful. :relaxed:

**Pull request closed without merging**
