### PR TITLE
added klu sparse solver with dependencies to SparseSuite

### PR DESCRIPTION
**Pull request by wibraun**

### CODE REVIEW

**Comment by sjoelund** [comment]
The PDFs and other documentation should not have been added

**Comment by adrpo** [comment]
Well, too late :)

**Comment by adrpo** [comment]
@sjoelund can you manipulate the commit to remove the pdfs and docs before we do the subproject commit in OMCompiler?

**Comment by sjoelund** [comment]
I push forced away this commit. I can go into the history to find it and merge it, I think.

**Comment by sjoelund** [comment]
I hope https://github.com/OpenModelica/OMCompiler-3rdParty/commit/c0a1749608a1cde7db6448934065681c529313ba works

**Pull request merged**
